"""Generate docker-compose.app.yml using published GHCR images (no build required)."""
import os

# Published image — both byoeb-chat and byoeb-kb use the same image, different CMD
_APP_IMAGE = "ghcr.io/a4i-tech/byoeb:latest"


def generate_app_compose(answers: dict, output_dir: str = ".") -> str:
    """
    Write docker-compose.app.yml to output_dir.
    Uses published registry images so no source code (git clone) is needed.
    Returns the absolute path of the written file.
    """
    include_qdrant = (
        answers.get("vector_store") == "qdrant"
        and answers.get("qdrant_mode") == "docker"
    )

    qdrant_service = ""
    if include_qdrant:
        qdrant_service = """
  qdrant:
    image: qdrant/qdrant:v1.9.0
    profiles: [qdrant]
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -sf http://localhost:6333/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
"""

    qdrant_volume = "\n  qdrant_data:" if include_qdrant else ""

    content = f"""\
# Generated by AshaBot Setup Wizard — https://github.com/A4i-tech/byoeb
# Uses pre-built images from GHCR. No git clone required.
services:
  byoeb-chat:
    image: {_APP_IMAGE}
    command: poetry run python3 -m byoeb.chat_app.run --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - local_media:/app/local_media_storage
      - vector_db:/app/vector_db
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: on-failure

  byoeb-kb:
    image: {_APP_IMAGE}
    command: poetry run python3 -m byoeb.kb_app.run
    ports:
      - "8001:5000"
    env_file:
      - .env.local
    volumes:
      - local_media:/app/local_media_storage
      - vector_db:/app/vector_db
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "byoeb-local-cluster"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
{qdrant_service}
volumes:
  mongo_data:
  kafka_data:
  local_media:
  vector_db:{qdrant_volume}
"""
    path = os.path.join(output_dir, "docker-compose.app.yml")
    os.makedirs(output_dir, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path
