"""Generate .env.local from wizard answers."""
import os
import secrets
from passlib.hash import bcrypt


def _kafka_block(a: dict) -> str:
    return f"""\
QUEUE_PROVIDER=kafka
KAFKA_BOOTSTRAP_SERVERS={a.get('kafka_bootstrap_servers', 'kafka:9092')}
KAFKA_CONSUMER_GROUP={a.get('kafka_consumer_group', 'byoeb')}
KAFKA_TOPIC_BOT={a.get('kafka_topic_bot', 'byoeb-bot')}
KAFKA_TOPIC_STATUS={a.get('kafka_topic_status', 'byoeb-status')}
KAFKA_TOPIC_DEAD_LETTER={a.get('kafka_topic_dlq', 'byoeb-dlq')}"""


def _azure_queue_block(a: dict) -> str:
    return f"""\
QUEUE_PROVIDER=azure_storage_queue
AZURE_STORAGE_QUEUE_ACCOUNT_URL={a.get('azure_storage_queue_account_url', '')}
AZURE_QUEUE_BOT={a.get('azure_queue_bot', '')}
AZURE_QUEUE_STATUS={a.get('azure_queue_status', '')}
AZURE_QUEUE_DEAD_LETTER={a.get('azure_queue_dead_letter', '')}"""


def _chroma_block(a: dict) -> str:
    return "VECTOR_STORE_TYPE=llama_index_chroma\nPERSIST_DIRECTORY=/app/vector_db"


def _qdrant_block(a: dict) -> str:
    mode = a.get("qdrant_mode", "memory")
    collection = a.get("qdrant_collection_name", "byoeb-kb")
    base = f"VECTOR_STORE_TYPE=qdrant\nQDRANT_COLLECTION_NAME={collection}"
    if mode == "memory":
        return base + "\nQDRANT_LOCATION=:memory:"
    elif mode == "docker":
        return base + "\nQDRANT_HOST=qdrant\nQDRANT_PORT=6333"
    else:
        return base + f"\nQDRANT_URL={a.get('qdrant_url','')}\nQDRANT_API_KEY={a.get('qdrant_api_key','')}"


def _azure_search_block(a: dict) -> str:
    return (
        "VECTOR_STORE_TYPE=azure_vector_search\n"
        f"AZURE_SEARCH_SERVICE_NAME={a.get('azure_search_service_name','')}\n"
        f"AZURE_SEARCH_INDEX_NAME={a.get('azure_search_index_name','')}\n"
        f"AZURE_SEARCH_API_KEY={a.get('azure_search_api_key','')}"
    )


def _storage_block(a: dict) -> str:
    if a.get("storage_backend") == "local":
        return (
            "STORAGE_BACKEND=local\n"
            f"LOCAL_STORAGE_PATH={a.get('local_storage_path', '/app/local_media_storage')}"
        )
    return (
        "STORAGE_BACKEND=azure\n"
        f"AZURE_STORAGE_BLOB_ACCOUNT_URL={a.get('azure_storage_blob_account_url','')}\n"
        f"AZURE_STORAGE_CONTAINER_NAME={a.get('azure_storage_container_name','')}"
    )


def generate_env(answers: dict, output_dir: str = ".") -> str:
    queue_block = _kafka_block(answers) if answers["queue"] == "kafka" else _azure_queue_block(answers)

    vs = answers["vector_store"]
    if vs == "llama_index_chroma":
        vector_block = _chroma_block(answers)
    elif vs == "qdrant":
        vector_block = _qdrant_block(answers)
    else:
        vector_block = _azure_search_block(answers)

    storage_block = _storage_block(answers)

    admin_hash = bcrypt.hash(answers["admin_password"])
    admin_secret = secrets.token_hex(32)
    auth_secret = secrets.token_hex(32)

    content = f"""\
# ============================================================
# AshaBot / BYOEB — generated by setup_wizard.py
# ============================================================

# --- Queue ---
{queue_block}

# --- Vector Store ---
{vector_block}

# --- File Storage ---
{storage_block}

# --- Database ---
MONGO_DB_CONNECTION_STRING={answers['mongo_uri']}

# --- OpenAI ---
OPENAI_API_KEY={answers['openai_api_key']}
OPENAI_ORG_ID={answers.get('openai_org_id', '')}

# --- WhatsApp ---
WHATSAPP_TOKEN={answers['whatsapp_token']}
WHATSAPP_PHONE_NUMBER_ID={answers['whatsapp_phone_id']}
WHATSAPP_VERIFY_TOKEN={answers.get('whatsapp_verify_token', 'byoeb-verify')}

# --- Auth ---
AUTH_TOKEN_SECRET={auth_secret}
AUTH_TOKEN_TTL_SECONDS=86400
AUTH_TOKEN_ALGORITHM=HS256
AUTH_TOKEN_ISSUER=byoeb
AUTH_TOKEN_AUDIENCE=byoeb

# --- Admin Panel ---
ADMIN_USERNAME={answers.get('admin_username', 'admin')}
ADMIN_PASSWORD_HASH={admin_hash}
ADMIN_SECRET_KEY={admin_secret}

# --- App ---
APP_ENV=LOCAL
"""
    path = os.path.join(output_dir, ".env.local")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path
